"""Initial postgres migration

Revision ID: cd4a5e53ceac
Revises: 
Create Date: 2022-09-23 12:27:06.694352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4a5e53ceac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User Email', sa.String(length=60), nullable=True),
    sa.Column('First name', sa.String(length=50), nullable=True),
    sa.Column('Last name', sa.String(length=50), nullable=True),
    sa.Column('Phone Number', sa.Numeric(), nullable=True),
    sa.Column('Password', sa.String(length=250), nullable=True),
    sa.Column('profilepic', sa.String(length=100), nullable=True),
    sa.Column('verifyans1', sa.String(length=200), nullable=True),
    sa.Column('verifyans2', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Phone Number'),
    sa.UniqueConstraint('User Email'),
    sa.UniqueConstraint('profilepic')
    )
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receivers_emails', sa.JSON(), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('email_text', sa.String(length=1000), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receivers', sa.JSON(), nullable=True),
    sa.Column('receivers_emails', sa.JSON(), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('email_text', sa.String(length=1000), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('star_marked', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('folder', sa.Enum('spam', 'primary', name='myenum'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('star_marked', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('senders')
    op.drop_table('receivers')
    op.drop_table('emails')
    op.drop_table('drafts')
    op.drop_table('users')
    # ### end Alembic commands ###
